version: '3.7'
services:
  backend:
    container_name: backend
    hostname: backend
    image: austin771/backend:latest
    env_file:
      - .env
    ports:
      - "9000:8080"
    depends_on:
      - database
  frontend:
    container_name: frontend
    hostname: frontend
    image: austin771/frontend:latest
    env_file:
      - .env
    ports:
      - "9001:80"
    restart: always
  database:
    container_name: database
    hostname: database
    image: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  data:
